// <auto-generated />
namespace Grikwa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Grikwav2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Grikwav2));
        
        string IMigrationMetadata.Id
        {
            get { return "201502012323517_Grikwav2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
